os: linux
dist: focal
language: node_js
node_js:
  - 18
  - 17
  - 16
  - 15
  - 14
  - 13
env:
  - VERBOSE=true
before_script:
  - npm run lint
  - npm run build
script:
  - jest --runInBand --coverage --forceExit --silent
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:	
  email:	
    on_success: never	
    on_failure: never