os: linux
dist: xenial
language: node_js
node_js:
  - node
env:
  - VERBOSE=true
before_script:
  - npm run lint
  - npm run build
script:
  - jest --runInBand --coverage --forceExit --silent
after_success:
  - codecov -f coverage/*.json
notifications:	
  email:	
    on_success: never	
    on_failure: never